---
title: "Mailles dans le temps"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  bookdown::html_document2:
    toc: true
    toc_float: true
params:
  date_min: '2010-01-01'
editor_options: 
  markdown: 
    wrap: sentence
---

```{r packages, include = FALSE}
# -*- coding: UTF-8 -*-

#' Packages
library(readr)
library(ggplot2)
library(dplyr)
library(stringi)
library(stringr)
library(sf)
library(rsample)
library(patchwork)
library(scales)
library(lubridate)
library(purrr)
library(forcats)
library(targets)
library(tarchetypes)
library(ggpubr)
library(collapse)
library(vegan)
library(tidyverse)   
library(ggspatial)   
library(tigris)
library(permute)
```

```{r mise-en-place}
source("~/work/AnalyseDonneesOpportunisteGMB/00_Nouveau/src/functions/divers.R")
wd <- set_wd()
source(paste0(wd$src, "functions/cartographie.R"))
source(paste0(wd$src, "functions/comparaison_dans_mailles.R"))
source(paste0(wd$src, "functions/GLM.R"))

```

```{r}
# Importations
Total <- st_read(paste0(wd$data,"Total.shp"))
```

```{r}
Total <- transform_Total()
Total <- ajout_famille_paysage()
```

```{r creation-mailles}
# Creation des mailles
library(sf)

Total <- creer_maille(bdd = Total, taille_en_km = 2)
Total <- creer_maille(bdd = Total, taille_en_km = 5)
Total <- creer_maille(bdd = Total, taille_en_km = 10)
Total <- creer_maille(bdd = Total, taille_en_km = 20)
```


```{r}
t2 <- tab_glm(61714, 60585)
reg <- glm(data = t2, 
           proportion_interet ~ year)
summary(reg)

t3 <- t2 %>%
  filter(!(proportion_interet %in% c(0, 1)))
reg <- glm(data = t3, 
           proportion_interet ~ year)
summary(reg)
plot(reg)

t3 <- t2 %>%
  filter(!(proportion_interet %in% c(0, 1)))
reg <- glm(data = t3, 
           proportion_interet ~ year+famille_paysage_max)
summary(reg)
plot(reg)


t4 <- t3 %>%
  mutate(year = as.factor(year))
reg <- glm(data = t4, 
           proportion_interet ~ year)
summary(reg)
```
