---
title: "Analyse descriptive des données opportunistes du GMB"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  bookdown::html_document2:
    toc: true
    toc_float: true
params:
  date_min: '2010-01-01'
editor_options: 
  markdown: 
    wrap: sentence
---

# Statistiques descriptives

```{r packages-imports, include = FALSE}
# Packages
library(readr)
library(ggplot2)
library(dplyr)
library(stringi)
library(stringr)
library(sf)
library(rsample)
library(patchwork)
library(scales)
library(viridis)
library(lubridate)
library(purrr)
library(forcats)
library(targets)
library(tarchetypes)
library(ggpubr)
library(collapse)
library(vegan)
library(permute)

source("~/work/AnalyseDonneesOpportunisteGMB/00_Nouveau/src/functions/divers.R")

wd <- set_wd()
source(paste0(wd$src,"functions/cartographie.R"), encoding="utf-8")
source(paste0(wd$src,"functions/comparaison_dans_mailles.R"), encoding="utf-8")


# Graine aléatoire
set.seed(12345)

# Importations
Total <- st_read(paste0(wd$data,"Total.shp"))
Total <- transform_Total()
```

```{r}


Total <- creer_maille(bdd = Total, taille_en_km = 2)
Total <- creer_maille(bdd = Total, taille_en_km = 5)
Total <- creer_maille(bdd = Total, taille_en_km = 10)
Total <- creer_maille(bdd = Total, taille_en_km = 20)

liste_cd_nom <- Total%>%
  st_drop_geometry()%>%
  distinct(cd_nom)

```

```{r}

pour_chaque_maillage(as.numeric(liste_cd_nom[[1]][1]))
pour_chaque_maillage(as.numeric(liste_cd_nom[[1]][2]))
pour_chaque_maillage(as.numeric(liste_cd_nom[[1]][3]))
pour_chaque_maillage(as.numeric(liste_cd_nom[[1]][4]))
pour_chaque_maillage(as.numeric(liste_cd_nom[[1]][5]))
pour_chaque_maillage(as.numeric(liste_cd_nom[[1]][6]))
pour_chaque_maillage(as.numeric(liste_cd_nom[[1]][7]))
pour_chaque_maillage(as.numeric(liste_cd_nom[[1]][8]))
pour_chaque_maillage(as.numeric(liste_cd_nom[[1]][9]))
pour_chaque_maillage(as.numeric(liste_cd_nom[[1]][10]))
pour_chaque_maillage(as.numeric(liste_cd_nom[[1]][11]))
pour_chaque_maillage(as.numeric(liste_cd_nom[[1]][12]))
pour_chaque_maillage(as.numeric(liste_cd_nom[[1]][13]))
pour_chaque_maillage(as.numeric(liste_cd_nom[[1]][14]))
pour_chaque_maillage(as.numeric(liste_cd_nom[[1]][15]))
pour_chaque_maillage(as.numeric(liste_cd_nom[[1]][16]))
pour_chaque_maillage(as.numeric(liste_cd_nom[[1]][17]))
pour_chaque_maillage(as.numeric(liste_cd_nom[[1]][18]))
pour_chaque_maillage(as.numeric(liste_cd_nom[[1]][19]))
pour_chaque_maillage(as.numeric(liste_cd_nom[[1]][20]))
pour_chaque_maillage(as.numeric(liste_cd_nom[[1]][21]))
pour_chaque_maillage(as.numeric(liste_cd_nom[[1]][22]))
pour_chaque_maillage(as.numeric(liste_cd_nom[[1]][23]))

```

