---
title: "Carte_Bretagne"
output: html_document
---

## Imports + transformations
```{r}
bretagne <- giscoR::gisco_get_nuts(resolution = "01", 
                                   country = "France", 
                                   nuts_level = 2) %>%
  subset(NUTS_NAME == "Bretagne") %>% 
  sf::st_transform(crs=2154)%>%
  sf::st_buffer(dist=200)%>%
  transforme_carte()

carte_bretagne_44 <- sf::st_read(
  paste0(wd$data,
         "masques/Masque_Bretagne_Continentale/Masque_Bretagne_Continentale.shp"
         ))%>%
  sf::st_transform(2154)%>%
  sf::st_buffer(dist = 200)%>%
  sf::st_transform(st_crs(4326))

bretagne_conti_buff <- bretagne %>%
  sf::st_intersection(carte_bretagne_44)
```


## Verif visuelle

```{r}
bretagne %>%
  ggplot()+geom_sf()

carte_bretagne_44 %>%
  ggplot()+geom_sf()

bretagne_conti_buff %>%
  ggplot()+geom_sf()
```

## Export
```{r}
sf::st_write(bretagne_conti_buff, 
             paste0(wd$data, "masques/Bretagne_Conti_Buffer/bretagne.shp"), 
             delete_layer = TRUE)
```

