---
title: "Nettoyage des donnees opportunistes DIR Ouest"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  bookdown::html_document2:
    toc: true
    toc_float: true
---

## Nettoyage de la base de donnee DIRO:
#Geometrie
```{r}
wd <- set_wd()

collision_faune_diro <- readr::read_csv(paste0(wd$data, "raw/collision_faune_diro.csv"))
```

```{r}
diro <- collision_faune_diro %>%
  dplyr::mutate(
    geom_x = as.numeric(stringr::str_match(geom, "POINT \\(([^ ]+)")[,2]),
    geom_y = as.numeric(stringr::str_match(geom, "POINT \\([^ ]+ ([^\\)]+)")[,2])
  )%>%
  dplyr::filter(!is.na(geom))

diro_sf <- sf::st_as_sf(diro, 
                        coords = c("geom_x", "geom_y"), 
                        crs = 2154)

diro_sf <- sf::st_transform(diro_sf, 
                        sf::st_crs(4326))


#importation des cartes
```

```{r}
carte_bretagne_44 <- sf::st_read(paste0(wd$data,                                    "masques/Masque_Bretagne_Continentale/Masque_Bretagne_Continentale.shp"
                                    )) %>%
  sf::st_transform(2154)%>%
  sf::st_transform(sf::st_crs(4326))

diro_conti <- sf::st_filter(diro_sf,
                            carte_bretagne_44, 
                            .predicate = sf::st_within)


diro_sf <- diro_conti%>%
  dplyr::filter(deppr != 44)

ggplot() +
   geom_sf(data = carte_bretagne_44) +
   geom_sf(data = diro_sf)

```

#Donnees
```{r}
diro_sf <- diro_sf %>%
   dplyr::filter(!(espece %in% c("amphibien", "amphibiens", "autre", "autre oiseau",
                          "castor", "chat", "chauve-souris", "chien", "chouette",
                          "nr", "oiseaux sauf rapace", "rapace diurne", 
                          "rapace nocturne", "rapaces nocturnes", "rapaces diurnes",
                          "reptile", "reptiles")))%>%
  dplyr::mutate(date = as.Date(paste(as.character(annee), mois, 01, sep="-")),
                espece = dplyr::if_else(commentaire == "Furet", 
                          "mustélidé", espece, missing=espece),
                espece = dplyr::if_else(startsWith(espece,"vison"), "mustélidé", espece, missing=espece),
                espece = dplyr::if_else(espece %in% c("martre", "belette", "fouine",
                                                      "hermine", "putois", "autre petit mustélidé"), 
                                        "mustélidé", espece, missing = espece )
        )%>% 
  dplyr::mutate(bdd_originale = "DIRO",
         technique_observation = "Vu",
         etat_biologique = "Trouvé mort : impact routier")%>%
  dplyr::mutate(espece = as.factor(espece)) %>%
  dplyr::select(-date_maj, -annee, -mois, -commentaire, -grp_espece)


test <- diro_sf%>%
  dplyr::mutate(cd_nom_t = dplyr::case_when(
    espece == "blaireau" ~ 60636,
    espece == "cerf/biche" ~ 61000,
    espece == "chevreuil" ~ 61057,
    espece == "écuireuil" ~ 61153,
    espece == "hérisson" ~ 60015,
        espece == "lapin" ~ 61714,
        espece == "lièvre" ~ 61678,
        espece == "loutre" ~ 60630,
        espece == "mustélidé" ~ 111,
        espece == "rangondin" ~ 61667,
        espece == "rat" ~ NA,
        espece == "rat musqué" ~ 61448,
        espece == "renard" ~ 60658,
        espece == "sanglier" ~ 60658,
    .default = NA
  ))%>%
  select(cd_nom_t, bdd_originale,espece, date, geom, geometry)

View(test)
summary(diro_sf$geometry)
summary(as.factor(diro_sf$espece))
summary(test$espece)
sf::st_write(diro_sf, paste0(wd$data, "derived/diro.shp"))

Morts_Naturalistes %>%
  
```
