---
title: "Creation/Ajout de sites et clusters dans la BDD Total"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  bookdown::html_document2:
    toc: true
    toc_float: true
---

```{r}

wd <- set_wd()

library(dplyr)

Total <- sf::st_read(paste0(wd$data,"derived/Total.shp"),
                     options = "ENCODING=UTF8")

Observateurs <- utils::read.csv(paste0(wd$data,"derived/Observateurs.csv"),
                                sep=";")

Total <- Total %>%
  transform_Total() %>%
  ajoute_clust_a_Total() %>%
  ajout_famille_paysage() %>%
  ajout_10x10_predetermine() 
```
```{r}
grille_10x10 <- sf::st_read(
  paste0(wd$data, "masques/Grille_10x10/Grille_10X10.shp")
)
RegionBretagneConti <- sf::st_read(
    paste0(wd$data, "masques/RegionBretagneConti/RegionBretagneConti.shp")
)
grille_10x10 <- grille_10x10 %>%
  transforme_carte()
RegionBretagneConti <- RegionBretagneConti %>%
  transforme_carte()
grille_10x10 <- sf::st_intersection(grille_10x10, 
                                    RegionBretagneConti)
  
# Ajout des variables
grille_10x10 <- cree_variable_struct(bdd_grille = grille_10x10, 
                                     bdd_tif = "Indice_Diversite_500m")
grille_10x10 <- cree_variable_struct(bdd_grille = grille_10x10, 
                                     bdd_tif = "Densite_Cultures_500m")
grille_10x10 <- cree_variable_struct(bdd_grille = grille_10x10, 
                                     bdd_tif = "Distance_EcotoneArbore")
grille_10x10 <- cree_variable_struct(bdd_grille = grille_10x10, 
                                     bdd_tif = "Distance_Littoral")
grille_10x10 <- cree_variable_struct(bdd_grille = grille_10x10, 
                                     bdd_tif = "Distance_Eau")
  
  
grille_10x10 <-  sf::st_transform(grille_10x10, sf::st_crs(Total))
  
Total <- grille_10x10 %>%
  dplyr::rename( Densite_Cultures = Densite_Cultures_500m,
                 Indice_Diversite = Indice_Diversite_500m ) %>%
  dplyr::select( Indice_Diversite, 
                 Densite_Cultures,
                 Distance_EcotoneArbore) %>%
  sf::st_join(Total, left = TRUE)

Total <- Total%>%
  select(-c(cmmnt_c, chmps_d))%>%
  filter(!is.na(date))
```

```{r}
sf::st_write(Total, paste0(wd$data, "derived/TotalComplet.shp"), 
             layer_options = "ENCODING=UTF-8")
```

