---
title: "Nettoyage des donnees opportunistes du GMB"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  bookdown::html_document2:
    toc: true
    toc_float: true
---

```{r nettoyage-contenue}
data_original_22_29 <- readr::read_delim(paste0(wd$data, "raw/GeoN_22-29.csv"), 
                                  delim = ";", 
                                  escape_double = FALSE, 
                                  trim_ws = TRUE)

data_original_35_56 <- readr::read_delim(paste0(wd$data, "raw/GeoN_35-56.csv"), 
                                  delim = ";", 
                                  escape_double = FALSE, 
                                  trim_ws = TRUE)

data_original_GeoRodents <- readr::read_delim(paste0(wd$data, "raw/VN_Rodentia.csv"), 
                                       delim = ";", 
                                       escape_double = FALSE, trim_ws = TRUE)

GeoN <- rbind(data_original_22_29, 
              data_original_35_56, 
              data_original_GeoRodents)

str(GeoN)
GeoN <- GeoN %>%
  dplyr::mutate(across(
    c(nom_valide,	nom_vernaculaire,
         ordre,
         observateurs,
         comment_occurrence,
         technique_observation,
         etat_biologique),
    ~stringi::stri_trans_general(., id = "Latin-ASCII")
  ))%>%
  dplyr::filter( !niveau_validation %in% c("Douteux","Invalide"))%>%
  dplyr::mutate(
    # Vison
    nom_vernaculaire = ifelse(cd_nom==194944, 
                              "Vison d'Europe, Vison, Petite loutre, Putois d'eau",
                              nom_vernaculaire),
    cd_nom = ifelse(cd_nom==194944, 60704, cd_nom),
    # Ecureuil
    nom_vernaculaire = ifelse(cd_nom==197486, 
                              "Ecureuil roux", 
                              nom_vernaculaire),
    cd_nom = ifelse(cd_nom==197486, 61153, cd_nom),
    # Martre
    nom_vernaculaire = ifelse(cd_nom==194481, 
                              "Martre des pins, Martre", 
                              nom_vernaculaire),
    cd_nom = ifelse(cd_nom==194481, 60658, cd_nom),
    # Rat
    nom_vernaculaire = ifelse(cd_nom==61585, 
                              "Rat surmulot, Surmulot, Rat d'egout", 
                              nom_vernaculaire))%>%
  dplyr::filter(!(cd_nom %in% c(194928, 197057, 61204)), 
                # Rat Fisher et ecureuil de Core
                !(cd_nom %in% c(60249,198197)), 
                # Taupes et Taupe d'Europe
                !(cd_nom %in% c(99999004, 99999005, 99999006)), 
                # NSP Carni
                !(cd_nom %in% c(60831, 60582, 60822, 60579, 199752)))%>% 
                # Carni Introduit
                # Carni introduit : 60831 Genette 
                # Introduit : chien viverrin, Raton laveur, Chacal dore, Furet
  dplyr::mutate(nombre = ifelse(nombre_max != nombre_min, 
                         median(c(nombre_max,nombre_min)),
                         nombre_min)
  )%>%
  dplyr::mutate(technique_observation = ifelse(
    !(technique_observation %in% c("Autres", "Entendu", "Ultrasons", "Vu")),
    "Indices",
    ifelse(technique_observation %in% c("Entendu", "Ultrasons"), 
           "Entendu",
           technique_observation)),
    technique_observation = ifelse(cd_nom == 60015, "Vu", technique_observation))%>%
  dplyr::mutate(etat_biologique = ifelse(etat_biologique == "NSP", 
                                  "Non renseigne", etat_biologique))%>%
  dplyr::filter(!jdd_nom %in% c(490,53))%>% 
  # 490: [visionature_opportunistic] Observations ponctuelles de Faune Bretagne
  # 53:  Donnes faunebretagne.org
  dplyr::mutate(technique_observation = ifelse(technique_observation == "Inconnu", 
                                        "Vu", technique_observation),
         champs_additionnels = NA)%>%
  dplyr::mutate(date = as.Date(date_debut),
         cd_nom = as.factor(cd_nom),
         ordre = as.factor(ordre),
         famille = as.factor(famille),
         etat_biologique=as.factor(etat_biologique),
         jdd_nom = as.factor(jdd_nom),
         nom_valide = as.factor(nom_valide),
         nom_vernaculaire = as.factor(nom_vernaculaire),
         technique_observation = as.factor(technique_observation),
         bdd_originale = as.factor("GeoNature"),
         observateurs = toupper(observateurs)
         )%>%
  dplyr::select("id_synthese",
         "date",
         "cd_nom",
         "nom_valide",	"nom_vernaculaire",
         "ordre",
         "nombre",
         "observateurs",	
         "geometrie_wkt_4326",	
         "x_centroid_4326",
         "y_centroid_4326",
         "comment_occurrence",
         "technique_observation",
         "etat_biologique", "bdd_originale", "champs_additionnels")

```

```{r}
gz_file <- gzfile(paste0(wd$data, "raw/VisioN_FB.gz"))
donnees_VisioNature_FB <- readr::read_delim(gz_file, 
                                            delim = ";", 
                                            escape_double = FALSE,
                                            trim_ws = TRUE)
  
VN_Rodentia <- readr::read_delim(paste0(wd$data, "raw/GN_Rodentia.csv"),
                          delim = ";", 
                          escape_double = FALSE, 
                          trim_ws = TRUE)

VisioN_FB <- rbind(donnees_VisioNature_FB, VN_Rodentia)

VisioN_FB <- VisioN_FB %>%
    dplyr::mutate(across(
    c(nom_valide,	nom_vernaculaire,
         ordre,
         observateurs,
         comment_occurrence,
         technique_observation,
         etat_biologique),
    ~stringi::stri_trans_general(., id = "Latin-ASCII")
  ))%>%
  dplyr::filter( !niveau_validation %in% c("Douteux","Invalide"))%>%
  dplyr::filter(technique_observation != "Restes dans pelote de rejection")%>%
  dplyr::mutate(technique_observation = ifelse(
    !is.na(comment_occurrence) & technique_observation == "Inconnu",
    ifelse(any(grepl("TAUPINIERE", toupper(gsub("[[:punct:]]", 
                                                "", 
                                                  comment_occurrence))),
               grepl("EMPREINTES", toupper(gsub(":punct:]]",
                                                "",
                                                  comment_occurrence, 
                                                  ))),
               grepl("TRACE", toupper(gsub(":punct:]]",
                                           "",
                                             comment_occurrence, 
                                           )))),
           "Indices",
           technique_observation),
    technique_observation))%>%
  dplyr::mutate(technique_observation = ifelse(technique_observation=="Entendu",
                                               "Entendu",
                                        technique_observation),
         technique_observation = ifelse(cd_nom == 60015, "Vu", technique_observation))%>%
  dplyr::filter(!(cd_nom %in% c(194928, 197057, 61204)), 
                # Rat Fisher et ecureil de Core
                !(cd_nom %in% c(60249,198197)), 
                # Taupes et Taupe d'Europe
                !(cd_nom %in% c(99999004, 99999005, 99999006)), 
                # NSP Carni
                !(cd_nom %in% c(60831, 60582, 60822, 60579, 199752)))%>% 
                # Carni Introduit
                # Carni introduit : 60831 Genette 
                # Introduit : chien viverrin, Raton laveur, Chacal dore, Putois domestique
  dplyr::mutate(technique_observation = ifelse(technique_observation == "Inconnu", 
                                               "Vu", technique_observation))%>%
  dplyr::mutate(etat_biologique = ifelse(champs_additionnels %in% c(
    "{'death_cause': 'ROAD_VEHICLE'}",
    "{'death_cause': 'OTHER_TRANSPORT'}",
    "{'death_cause': 'UNKNOWN_TRANSPORT'}"),
    "Trouve mort : impact routier",
    etat_biologique),
    etat_biologique = ifelse(((champs_additionnels == "{'death_cause': 'UNKNOWN'}") & (etat_biologique == "Trouve mort") & grepl("ROUT", toupper(comment_occurrence))), 
                                  "Trouve mort : impact routier",
                                  etat_biologique)
         )%>%
  dplyr::mutate(nombre = nombre_min, # nombre max = soit na soit nombre min
         date = as.Date(date_debut),
         cd_nom = as.factor(cd_nom),
         ordre = as.factor(ordre),
         famille = as.factor(famille),
         etat_biologique=as.factor(etat_biologique),
         jdd_nom = as.factor(jdd_nom),
         nom_valide = as.factor(nom_valide),
         nom_vernaculaire = as.factor(nom_vernaculaire),
         technique_observation = as.factor(technique_observation),
         bdd_originale = as.factor("VisioNature"),
         observateurs = toupper(observateurs))%>%
  dplyr::mutate(observateurs = ifelse(!is.na(observateurs), 
                               toupper(observateurs), NA))%>%
  dplyr::select("id_synthese",
         "date",
         "cd_nom",
         "nom_valide", "nom_vernaculaire",
         "ordre",
         "nombre",
         "observateurs",	
         "geometrie_wkt_4326",	
         "x_centroid_4326",
         "y_centroid_4326",
         "comment_occurrence",
         "technique_observation",
         "etat_biologique", "bdd_originale", "champs_additionnels")

Total <- rbind(VisioN_FB, GeoN)

Total <- Total %>%
  dplyr::mutate(observateurs = gsub("-", " ", observateurs), # enlever tirets
         observateurs = janitor::make_clean_names(observateurs, 
                                                  allow_dupes = TRUE), # Accents
         observateurs = toupper(observateurs),
         observateurs = ifelse(observateurs == "NA", NA, observateurs)#majuscule
  )%>%
  dplyr::mutate(observateurs = as.factor(replace(
    as.character(observateurs),
    which(is.na(observateurs)),
    paste("NA_", seq_len(sum(is.na(observateurs))), sep="")))) # donner le nom : NA_1, NA_2, ...

any(duplicated(Total))
```

Maintenant on nettoie selon les coordonnees geographiques:
- suppression des rongeurs en Loire Atlantique
- suppression des iles 

```{r nettoyage-cartographique}
Total_sf <- sf::st_as_sf(Total,
                     coords = c("x_centroid_4326", "y_centroid_4326"), 
                     crs = 4326)
CRS = sf::st_crs(Total_sf)


#importation des cartes
carte_bretagne_44 <- sf::st_read(paste0(wd$data,
                                    "masques/Masque_Bretagne_Continentale/Masque_Bretagne_Continentale.shp"
                                    ))
carte_bretagne_44 <- sf::st_transform(carte_bretagne_44, 2154)
carte_bretagne_44 <- sf::st_buffer(carte_bretagne_44, dist = 200)
carte_bretagne_44  <- sf::st_transform(carte_bretagne_44, st_crs(CRS))


carte_44 <- sf::st_read(paste0(wd$data,
                           "masques/Masque_44/Masque44.shp"))
carte_44 <- sf::st_transform(carte_44, 2154)
carte_44 <- sf::st_buffer(carte_44, dist = 200) 
# Il nous manquera peut etre qqes donnes entre le 44 et le 35 mais j'espere pas trop grave?
carte_44 <- sf::st_transform(carte_44, st_crs(CRS))


#filtre
total_bretagne_44 <- sf::st_filter(Total_sf, carte_bretagne_44, .predicate = st_within)
total_44 <- sf::st_filter(Total_sf, carte_44, .predicate = st_within)
total_44_id_synthese <- total_44 %>%
  sf::st_drop_geometry() %>%
  dplyr::select(id_synthese)

que_bretagne <- anti_join(total_bretagne_44, 
                          total_44_id_synthese, 
                          by = "id_synthese")

# Verifications
# ggplot() +
#   geom_sf(data = que_bretagne) +
#   labs(title = "Points en Bretagne (sauf dans le 44)")


sf::st_write(que_bretagne, 
             paste0(wd$data, "derived/Total.shp"), 
             layer_options = "ENCODING=UTF-8",
             delete_dsn = TRUE)
```

