###########################################
#######  VARIABLES DES SITES  #############
###########################################

# DEFINITION DE LA GRILLE EN REGION BRETAGNE CONTINENTALE

```{r}
grille_10x10 <- sf::st_read(
  paste0(wd$data, "masques/Grille_10x10/Grille_10X10.shp")
)
RegionBretagneConti <- sf::st_read(
  paste0(wd$data, "masques/RegionBretagneConti/RegionBretagneConti.shp")
)
RegionBretagneConti <- RegionBretagneConti%>%
  transforme_carte()%>%
  sf::st_transform(2154)%>%
  sf::st_buffer(dist = 200)%>%
  transforme_carte()

grille_10x10 <- grille_10x10 %>%
  transforme_carte() %>%
  sf::st_intersection(RegionBretagneConti)%>%
  dplyr::arrange(CODE_10KM)%>%
  dplyr::select(CODE_10KM)

grille_10x10 <- grille_10x10%>%
  dplyr::filter(sf::st_is(grille_10x10,c("POLYGON","MULTIPOLYGON")))
```


# VARIABLES STRUCTURANTES
```{r}
var_noms <- c("Indice_Diversite_500m", "Densite_Cultures_500m", 
              "Distance_EcotoneArbore", "Distance_Littoral", "Distance_Eau")

for(var in var_noms) {
  raster_path <- paste0(wd$data, "masques/VariablesStructurates/", var, ".tif")
  rast <- terra::rast(raster_path)
  terra::crs(rast) <- "EPSG:2154"
  grille_10x10 <- sf::st_transform(grille_10x10, crs = "EPSG:2154")
  vals <- exactextractr::exact_extract(rast, grille_10x10, 'mean')
  grille_10x10[[var]] <- vals
}
```

Suppression car hors du territoire -> Ca nous corrige le problème qu'on avait avec les individus dans la partie bluffé du 44.
```{r}
grille_10x10 <- grille_10x10%>%
  dplyr::filter(!is.na(Distance_Littoral))
```

```{r}
var_noms <- c("Indice_Diversite_500m", "Densite_Cultures_500m", 
              "Distance_EcotoneArbore", "Distance_Littoral", "Distance_Eau")

for(var in var_noms) {
  print(grille_10x10%>%
    ggplot()+
    geom_sf(aes(fill = .data[[var]]))
    )
}
```

# FAMILLES DE PAYSAGES
```{r}
famille_paysage <- sf::st_read(
  paste0(wd$data, "masques/famille_paysage/familles_paysages.shp")
)
famille_paysage <- famille_paysage %>%
  dplyr::rename(Nom_paysage = NOM,
                Famille_paysage = FAMILLE)%>%
  dplyr::mutate_if(is.character,as.factor)%>%
  dplyr::select(Nom_paysage, Famille_paysage)

grille_10x10 <- grille_10x10 %>%
  sf::st_join(famille_paysage)
```

```{r}
grille_10x10%>%
  ggplot() + geom_sf(aes(fill=Famille_paysage))

grille_10x10%>%
  dplyr::filter(is.na(Famille_paysage))%>%
  ggplot() + geom_sf(aes(fill=Famille_paysage))

grille_10x10%>%
  dplyr::filter(is.na(Famille_paysage))%>%
  select(CODE_10KM)
grille_10x10_sNA <- grille_10x10%>%
  dplyr::filter(!is.na(Famille_paysage))
  
grille_10x10 <- grille_10x10 %>%
    dplyr::mutate(Famille_paysage = ifelse(is.na(Famille_paysage),  
                                      grille_10x10$Famille_paysage[sf::st_nearest_feature(grille_10x10, 
                                                                                 grille_10x10_sNA)], 
                                   Famille_paysage))
```



# TAILLE DE LA CELLULE
```{r}
grille_10x10 <- grille_10x10 %>%
  sf::st_transform(2154) %>%
  dplyr::mutate(aire_km2 = as.numeric(sf::st_area(grille_10x10)/1000000)) %>%
  transforme_carte()%>%
  dplyr::filter(aire_km2 > 2)
```

```{r}
grille_10x10%>%
  ggplot()+geom_sf(aes(fill=aire_km2))
```

# COORDONNEES DES CENTROIDS
```{r}
centroids <- sf::st_centroid(grille_10x10)
centroid_coords <- sf::st_coordinates(centroids)

grille_10x10_centroids <- grille_10x10 %>%
  dplyr::mutate(
    X_10km = centroid_coords[, "X"],
    Y_10km = centroid_coords[, "Y"]
  ) %>%
  dplyr::select(CODE_10KM, X_10km, Y_10km)

grille_10x10 <- grille_10x10 %>%
  dplyr::left_join(
    as.data.frame(grille_10x10_centroids),
    by = "CODE_10KM"
  )
```


# Exports
Export sous forme shapefile 
```{r}
grille_10x10%>%
  dplyr::select(-geometry.y)%>%
  sf::st_write(paste0(wd$data, "derived/VariablesSite.shp"), 
               delete_dsn = TRUE)
```

Export sous forme csv
```{r}
grille_10x10%>%
  dplyr::select(-geometry.y)%>%
  sf::st_drop_geometry()%>%
  utils::write.csv(paste0(wd$data, "derived/VariablesSite.csv"))
```

