---
title: "Semaine 9"
date: "04/08 - 08/08"
output:
  bookdown::html_document2:
    toc: true
    toc_float: true
---

# Modèles d'occupancy

## Bibliographie

-   Ref de Simon Lacombe :

    -   [Occupancy Modeling, Morgan Byrne, James Golde](https://kevintshoemaker.github.io/NRES-746/Occupancy.html)

        -   unmarked::occu mais aussi bayesien avec Just Another Gibbs Sampler.

    -   [Citizen science indicates significant range recovery and defines new conservation priorities for Earth's most endangered pinniped in Greece](https://zslpublications.onlinelibrary.wiley.com/doi/10.1111/acv.12806)

        -   Et le code associé : [https://oliviergimenez.github.io/monkseal-occupancy/https://oliviergimenez.github.io/monkseal-occupancy/](https://oliviergimenez.github.io/monkseal-occupancy/){.uri} ( N'utilise pas la fction occu mais fait un modèle de bayésien avec Gibbs mais pas même que au dessus (Bayesian inference using Gibbs sampling) )
        -   interessant pour les choix qu'ils ont fait.

-   Ref de Franck Simonnet (pas encore bien lu):

    -   [Estimating Site Occupancy Rates When Detection Probabilities Are Less Than One](https://www.researchgate.net/publication/228821155_Estimating_Site_Occupancy_Rates_When_Detection_Probabilities_Are_Less_Than_One){.uri} -> Lu

    -   [Journal of Biogeography Journal of Biogeography Free Access Predicting species distributions from checklist data using site-occupancy models](https://onlinelibrary.wiley.com/doi/10.1111/j.1365-2699.2010.02345.x)

-   Autres références :

    -   Article sur le sujet que j'avais lu le mois dernier à relire : [https://docs.google.com/document/d/1noZm3QprMJMsYErZo8bSeARPTEVTstCk0HPS-MLO-V0/edit?tab=t.0](#0){.uri} ( ils utilisaient JAGS et ca marchait bien de mémoire)

    -   Occupancy modeling. Présente les hypothèses et les problèmes si les hypothèses ne sont pas vérifiés. [https://pubs.usgs.gov/fs/2005/3096/fs](https://pubs.usgs.gov/fs/2005/3096/fs20053096.pdf){.uri} [20053096.pdf](https://pubs.usgs.gov/fs/2005/3096/fs20053096.pdf){.uri}

    -   Exemples d'utilisation du package.

        -   <https://cran.r-project.org/web/packages/unmarked/vignettes/occuComm.html>

        -   <https://cran.r-project.org/web/packages/unmarked/vignettes/colext.html>

        -   Tests + puissance : <https://cran.r-project.org/web/packages/unmarked/vignettes/powerAnalysis.html>

https://www.youtube.com/watch?v=rpjVrFI_dr8&t=577s
+ livre qui est top
## Debut de modelisation

Cette semaine,

-   Il y avais des problèmes dans les variables d'environnement, donc j'en ai profité pour aussi supprimer tous les accents.

-   J'ai donc également recalculé les variables d'environnement [https://rpubs.com/valentine_cleach/variables_site](#0){.uri}

-   j'ai supprimé 11 sites avec une aire strictement inférieur a 2km\^2. Répartition assez aléatoire (nord, sud et est de la map) donc ca passait je trouve, et dans le 2e article (sur le phoque) c'est un choix qu'ils ont fait afin de ne pas avoir de sites ou il y a trop peu de chances d'être visité plusieurs fois.

-   J'ai lu les articles et leur code pour commencer a implementer un modèle de site occupancy (d'abord sur le lapin) voir ci dessous ou sur [ce lien](https://rpubs.com/valentine_cleach/occupancylapindegarenne)

En étudiant le lapin de garenne avec 2 periodes:

-   2005 - 2014

-   2015-2024

Nous avons une augementation significative du lapin, sans implémenter des variables d'environnement.

En regardant il y a très peu de sites présent de 2005 a 2010 (peu d'observations et peu d'observateurs). Essayer de faire 2010 - 2015 puis 2019 - 2024 et on ca permet de mettre notre hypothèse que les individus ne peuvent pas varier au sein d'une periode. (article sur les phoques ou le fact sheet *Occupancy models to study wildlife*). Ou alors mettre 3 periodes, de 4 ou 5 ans? pour include 2015-2019? Essayer.

Ne pas inclure car seulement après 2014 / 2015 donc pour ce modèle ca ne marcherait surement pas car on veut comparer. Il y aura probablement une fausse augementation des sites ou les individus sont detectés.

Inclure le mois de détection? -\> souvent fait, et une partie du code déjà prêt juste a re-incorporer. Pas sur que ca sera très intéressant, mais ca doit pas être trop compliqué ?

Hypothèse de sites non continue -\> Continuous-space occupancy models? + compliqué et a étudier le truc après. Peut etre pas nécéssaire.

### But semaine pro:

-   Lire plus la biblio.

-   Avoir des modèles qui marchent (tests okay, significatif et bien) au moins le lapin, si possible les autres espèces. Voir ce que ca fait de centrer reduire par ex etc. Trouver cmt savoir quelles variables sont les + intéressantes.

-   Si du temps, faire avec JAGS, on a le code déjà donc juste a ajouter nos variables, et laisser tourner la nuit...
