---
title: "Semaine 9"
date: "04/08 - .../08"
output:
  bookdown::html_document2:
    toc: true
    toc_float: true
---

# Modèles d'occupancy

## Bibliographie -\> but : lire + recap d'ici demain soir, max mercredi soir.

-   Ref de Simon Lacombe :

    -   [Occupancy Modeling, Morgan Byrne, James Golde](https://kevintshoemaker.github.io/NRES-746/Occupancy.html)

    -   [Citizen science indicates significant range recovery and defines new conservation priorities for Earth's most endangered pinniped in Greece](https://zslpublications.onlinelibrary.wiley.com/doi/10.1111/acv.12806)

        -   Et le code associé : [https://oliviergimenez.github.io/monkseal-occupancy/https://oliviergimenez.github.io/monkseal-occupancy/](https://oliviergimenez.github.io/monkseal-occupancy/){.uri}

-   Ref de Franck Simonnet :

    -   [Estimating Site Occupancy Rates When Detection Probabilities Are Less Than One](https://www.researchgate.net/publication/228821155_Estimating_Site_Occupancy_Rates_When_Detection_Probabilities_Are_Less_Than_One){.uri}

    -   [Journal of Biogeography Journal of Biogeography Free Access Predicting species distributions from checklist data using site-occupancy models](https://onlinelibrary.wiley.com/doi/10.1111/j.1365-2699.2010.02345.x)

-   Autres références :

    -   ??

    -   Déjà un article de lu sur le sujet le mois dernier a retrouver aussi ?

    -   reference du truc github de occupancy modeling. Présente les hypothèses et les problèmes si les hypothèses ne sont pas vérifiés. <https://pubs.usgs.gov/fs/2005/3096/fs20053096.pdf>

    -   autres ex d'utilisation du package.

        -   <https://cran.r-project.org/web/packages/unmarked/vignettes/occuComm.html>

        -   <https://cran.r-project.org/web/packages/unmarked/vignettes/colext.html>

        -   Tests + puissance : <https://cran.r-project.org/web/packages/unmarked/vignettes/powerAnalysis.html>

    -   

## Debut de modelisation -\> **but : Au moins un modèle qui marche avec méthode fréquentiste. Cool si semaine pro je fais pareil mais bayesien (?)**

## 

Faudrait il enlever les petits sites? Ils peuvent etre intéressant (surtout c'est vers la cote souvent et bcp de lapins par là), mais rends + compliqué de trouver une espèce a cet endroit là precisement.

Aussi, avant de continuer, faudrait tout passer en sans accents... Il etait temps (:

En étudiant le lapin de garenne avec 2 periodes:

-   2005 - 2014

-   2015-2024

Nous avons une augementation significative du lapin... (Je crois, même si je ne comprends pas encore tt a fait ce modèle). Je n'ai pas encore inclue de variables d'environnement etc, juste les dates.

En regardant il y a très peu de sites présent de 2005 a 2010 (peu d'observations et peu d'observateurs). Essayer de faire 2010 - 2015 puis 2019 - 2024 et on ca permet de mettre notre hypothèse que les individus ne peuvent pas varier au sein d'une periode. Ou alors mettre 3 periodes, de 4 ou 5 ans? pour include 2015-2019?

Quand inclure DIRO? Ne pas inclure car seulement après 2015...? (enfin j'imagine)

Inclure le mois de détection? -\> souvent fait, et une partie du code déjà prêt juste a re-incorporer. Nécessaire ou intéressant pas sur.?

Hypothèse de sites non continue -\> Continuous-space occupancy models? + compliqué et a étudier le truc après. Peut etre pas nécéssaire.

Il y avais des problèmes dans les variables d'environnement, donc j'en ai profité pour aussi supprimer tous les accents, et refaire différamment les variables d'environnement.

Suppression de 11 sites qui ont une aire strictement inférieur a 2km\^2. Répartition assez aléatoire (nord, sud et est de la map).

Voir le nettoyage sur ce Rmd: <https://rpubs.com/valentine_cleach/variables_site>
